version: '3.3'

volumes:
  postgres_data: {}

services:
  backend:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: on-failure
    env_file: .env.docker
    command: /run.sh


  postgres:
    image: postgres:12.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.docker
    ports:
      - "5432:5432"
